apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Model server
  annotations:
    argocd/app-selector: backstage-name=${{ values.projectName }},modelserver=${{ values.name }}
  tags:
    - model-server
spec:
  type: model-server
  lifecycle: production
  owner: ${{ values.owner }}
  subcomponentOf: ${{ values.projectEntity }}
  dependsOn:
    - ${{ values.rootSelfServiceRepo }}
    - ${{ values.projectEntity }}
    - ${{ values.dataConnectorEntity }}
    - ${{ values.modelEntity }}