apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Model server
  argocd/app-selector: backstage-name=${{ values.projectName }},model-server=${{ values.name }}
  tags:
    - model-server
spec:
  type: model-server
  lifecycle: production
  owner: ${{ values.owner }}
  subcomponentOf: ${{ values.subcomponentOf }}
  dependsOn:
    - ${{ values.dependsOn }}