apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: root-self-service-repository
  title: Root Self-Service Repository
  description: |
    This repository serves as the root self-service repository for GitLab and ArgoCD integration.
    It enables teams to attach their team-based repositories and synchronize applications with 
    the root repository, ensuring a streamlined continuous deployment process via ArgoCD.
  annotations:
    argocd/app-name: root-self-service-repository
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: self-service/root-self-service-repository
spec:
  type: service
  system: root-self-service
  lifecycle: production
  owner: devops-team
