apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Data connector
  annotations:
    argocd/app-selector: backstage-name=${{ values.projectName }},dataconnector=${{ values.name }}
  tags:
    - data-connector
spec:
  type: data-connector
  lifecycle: production
  owner: ${{ values.owner }}
  subcomponentOf: ${{ values.subcomponentOf }}
  dependsOn:
    {{ for item in values.dependsOn }}
      - {{ item }}
    {{ endfor }}