apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: root-self-service-repository
  title: Create a GitLab Root Self-Service Repository (One-Time Use)
  description: |
    One-Time Use: This template automates the creation of a GitLab root repository from a predefined 
    skeleton and configures an ArgoCD application to automatically synchronize changes from the 
    repository. The root repository is intended to serve as the central point for managing applications. 
    Any team-based self-service repositories will attach their applications to this root repository 
    and will be synced from it, ensuring a cohesive and streamlined continuous deployment process. 
    This template is intended for single use to prevent conflicts with the root structure.
  tags:
    - gitlab
    - argocd
    - automation
    - devops
    - poc-examples
    - self-service
    - one-time-use

spec:
  owner: devops-team
  system: self-service
  type: Service
  parameters:

    - title: ArgCD Application Information
      ui:group: argocd
      required:
        - argoInstance
        - gitlabInstance
      properties:
        argoInstance:
          title: ArgoCD Instance
          type: string
          description: The ArgoCD instance that will manage this application
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: System
                spec.type: argocd
        gitlabInstance:
          title: GitLab Instance
          type: string
          description: The GitLab instance to create a self-service repository in
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: System
                spec.type: gitlab
        gitlabOwner:
          title: GitLab Owner
          type: string
          default: self-provisioned
          description: The GitLab repository owner
        gitlabRepository:
          title: GitLab Repository
          type: string
          default: manifests
          description: The GitLab self-service repository
  steps:

    ##########################
    ## Template the Repository
    ##########################
    - id: pullRepositorySkeleton
      name: "Pull Self-Service Skeleton"
      action: fetch:template
      input:
        url: './skeleton'
        copyWithoutTemplating:
          - README.md
          - LICENSE
          - catalog-info.yaml
          - projects
        values:
          targetRevision: "main"
          domain: kechung.tamlab.rdu2.redhat.com #${{ parameters.argoInstance | parseEntityRef | pick('name') }}
          path: "projects"
          projectName: "system"

    #################################
    ## Create Self-Service Repository
    #################################
    - id: publish
      name: "Create Self-Service Repository"
      action: publish:gitlab
      input:
        allowedHosts:
          - ${{ parameters.gitlabInstance | parseEntityRef | pick('name') }}
        description: |
          Self-Service Repository
        repoUrl: ${{ parameters.gitlabInstance | parseEntityRef | pick('name') }}
        #repoUrl: gitlab.consulting.redhat.com?owner=${{ parameters.gitlabOwner }}&repo=${{ parameters.gitlabRepository }}
        #repoUrl: ${{ parameters.gitlabInstance | parseEntityRef }}?owner=${{ parameters.gitlabOwner }}&repo=${{ parameters.gitlabRepository }}
        defaultBranch: main

    #################################
    ## ArgoCD Resources Configuration
    #################################
    - id: createArgocdResources
      name: "Create ArgoCD Resources"
      action: argocd:create-resources
      input:
        appName: "root-self-service"
        argoInstance: ${{ parameters.argoInstance | parseEntityRef | pick('name') }}
        namespace: "openshift-gitops"
        repoUrl: "${{ steps['publish'].output.remoteUrl }}.git"
        path: "_init_"

    ########################
    ## Register Catalog Info
    ########################
    - id: registerCatalog
      name: "Register Catalog Info"
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps["publish"].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: GitOps Application
        url: ${{ parameters.argoInstance | parseEntityRef | pick('name') }}/applications/openshift-gitops/root-self-service
      - title: GitLab Repository
        url: ${{ steps['publish'].output.remoteUrl }}
