apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: root-self-service-repository
  title: Create a GitLab Root Self-Service Repository (One-Time Use)
  description: |
    One-Time Use: This template automates the creation of a GitLab root repository from a predefined 
    skeleton and configures an ArgoCD application to automatically synchronize changes from the 
    repository. The root repository is intended to serve as the central point for managing applications. 
    Any team-based self-service repositories will attach their applications to this root repository 
    and will be synced from it, ensuring a cohesive and streamlined continuous deployment process. 
    This template is intended for single use to prevent conflicts with the root structure.
  tags:
    - gitlab
    - argocd
    - automation
    - devops
    - poc-examples
    - self-service
    - one-time-use

spec:
  owner: devops-team
  system: self-service
  type: Service
  parameters:

    - title: ArgCD Application Information
      ui:group: argocd
      required:
        - argoInstance
      properties:
        argoInstance:
          title: ArgoCD Instance
          description: The ArgoCD instance that will manage this application. Choose from available instances.
          enum:
            - main
          type: string

    - title: GitLab Repository Information
      required:
        - gitlabInstance
        - gitlabOwner
        - gitlabRepository
        - gitlabBranch
      properties:
        gitlabInstance:
          title: GitLab Instance
          type: string
          description: GitLab instance
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Resource
                spec.type: gitlab
        gitlabOwner:
          title: GitLab Owner
          type: string
          default: self-provisioned
          description: GitLab repository owner
        gitlabRepository:
          title: GitLab Repository
          type: string
          default: manifests
          description: GitLab self-service repository
        gitlabBranch:
          title: GitLab Branch
          type: string
          default: main
          description: GitLab repository branch

  steps:

    - action: catalog:fetch
      id: fetchGitlabEntity
      name: Fetch Gitlab Entity
      input:
        entityRef: ${{ parameters.gitlabInstance }}


    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: ${{ steps['fetchGitlabEntity'] | dump }}

    - id: log2-message
      name: Log2 Message
      action: debug:log
      input:
        message: ${{ steps['fetchGitlabEntity'].output.entity.spec.url | dump }}

    ##########################
    ## Template the Repository
    ##########################
    - id: pullRepositorySkeleton
      name: "Pull Self-Service Skeleton"
      action: fetch:template
      input:
        url: './skeleton'
        copyWithoutTemplating:
          - README.md
          - LICENSE
          - catalog-info.yaml
          - projects
        values:
          targetRevision: "main"
          domain: kechung.tamlab.rdu2.redhat.com # ${{ ${{ steps.requestDynamicData.output.body["DOMAIN"] }}
          path: "projects"
          projectName: "system"

    #################################
    ## Create Self-Service Repository
    #################################
    - id: publish
      name: "Create Self-Service Repository"
      action: publish:gitlab
      input:
        allowedHosts:
          - ${{ steps['fetchGitlabEntity'].output.entity.spec.url }}
        description: |
          Self-Service Repository
        repoUrl: ${{ steps['fetchGitlabEntity'].output.entity.spec.url }}?owner=${{ parameters.gitlabOwner }}&repo=${{ parameters.gitlabRepository }}
        #repoUrl: gitlab.consulting.redhat.com?owner=${{ parameters.gitlabOwner }}&repo=${{ parameters.gitlabRepository }}
        defaultBranch: ${{ parameters.gitlabBranch | main }}

    #################################
    ## ArgoCD Resources Configuration
    #################################
    - id: createArgocdResources
      name: "Create ArgoCD Resources"
      action: argocd:create-resources
      input:
        appName: "root-self-service"
        argoInstance: ${{ parameters.argoInstance }}
        namespace: "openshift-gitops"
        repoUrl: "${{ steps['publish'].output.remoteUrl }}.git"
        path: "_init_"

    ########################
    ## Register Catalog Info
    ########################
    - id: registerCatalog
      name: "Register Catalog Info"
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps["publish"].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: GitOps Application
        url: https://openshift-gitops-server-openshift-gitops.apps.${{ steps['requestDynamicData'].output.body["DOMAIN"] }}/applications/openshift-gitops/root-self-service
      - title: GitLab Repository
        url: ${{ steps['publish'].output.remoteUrl }}
