apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "${{ values.repoName }}"
  namespace: "openshift-gitops"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {%- if values.labels.project %}
  labels:
    backstage-name: ${{ values.labels.project }}
    {%- if values.labels.dataConnector.length %}
    dataconnector: ${{ values.labels.dataConnector }}
    {%- endif %}
    {%- if values.labels.modelServer.length %}
    modelserver: ${{ values.labels.modelServer }}
    {%- endif %}
    {%- if values.labels.model.length %}
    model: ${{ values.labels.model }}
    {%- endif %}
  {%- endif %}
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
                - application: "${{ values.repoName }}"
                  namespace: "${{ values.namespace }}"
                  chart: 
                    name: "${{ values.chart.name }}"
                    url: "${{ values.chart.chartUrl }}"
                    version: "${{ values.chart.chartVersion }}"
                  values: |
${{ values.valuesObject | safe | indent(20, true) }}
  template:
    metadata:
      name: "{{ .application }}"
    spec:
      destination:
        namespace: "{{ .namespace }}"
        server: "{{ .server }}"
      source:
        chart: "{{ .chart.name }}"
        targetRevision: "{{ .chart.version }}"
        repoURL: "{{ .chart.url }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "openshift-gitops"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{- if (index . "values") }}
          values: |
            {{- .values | nindent 12 }}
        {{- end }}
