apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Model
  annotations:
    argocd/app-selector: backstage-name=${{ values.projectName }},model=${{ values.name }}
  tags:
    - model
spec:
  type: model
  revision: ${{ values.revision }}
  repository: ${{ values.repository }}
  lifecycle: production
  owner: ${{ values.owner }}
  subcomponentOf: ${{ values.projectEntity }}
  dependsOn:
    - ${{ values.rootSelfServiceRepo }}
    - ${{ values.projectEntity }}
    - ${{ values.dataConnectorEntity }}